#!/bin/ksh

##
# mm-browser: set the web browser to call when clicking links in MailMate
# 
# Original author: O'Shaughnessy Evans <shaug+mailmate@wumpus.org>
##

typeset -r browser_name=$1
typeset -r known_browsers="chrome, firefox, safari"
browser_string=

case $browser_name in
chrome|com.google.Chrome)
    browser_string="com.google.Chrome"
    ;;
firefox|org.mozilla.firefox)
    browser_string="org.mozilla.firefox"
    ;;
safari|com.apple.safari)
    browser_string="com.apple.Safari"
    ;;
"")
    print "MailMate browser: \c"
    defaults read com.freron.MailMate OakBrowserAppBundleIdentifier
    print "Browser options: $known_browsers"
    exit 0
    ;;
*)
    app_dir=
    if [[ -d ~/Applications/$browser_name.app ]]; then
        app_dir=~/Applications/$browser_name.app
    elif [[ -d /Applications/$browser_name.app ]]; then
        app_dir=/Applications/$browser_name.app
    fi

    if [[ -z "$app_dir" ]]; then
        print "failure: couldn't find an application string for $browser_name"
        exit 1
    fi

    browser_string=$(defaults read $app_dir/Contents/Info.plist CFBundleIdentifier)
    if [[ -z "$browser_string" ]]; then
        print "failure: couldn't read the identifier for $browser_name"
        exit 2
    fi
    ;;
esac

printf "MailMate browser: %s -> " "$(defaults read com.freron.MailMate OakBrowserAppBundleIdentifier)"

if [[ -n "$browser_string" ]]; then
    defaults write com.freron.MailMate OakBrowserAppBundleIdentifier -string $browser_string
fi

defaults read com.freron.MailMate OakBrowserAppBundleIdentifier
